### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#275]
## Action Plan

- [x] Sidebar styles
- [x] Content styles
- [x] Add footer
- [x] Only include from bootstrap what we use, rather than bundling all this stuff we don't need
- [ ] Highlight currently selected items in the sidebar modules/sections 
- [ ] Pull fonts not from `templates/fonts` but from `node_modules/font-awesome` instead
- [x] Remove twitter bootstrap (we use too little of it) and replace it with just normalize plus custom layout
- [x] Review mobile layout
- [x] Update search to use the json data instead of markup (PR #322)
- [x] Remove functions from the sidebar list (PR #320)
- [ ] Add nesting level for the first level of modules
- [x] Show search results in the main content area (PR #322)
- ~~Add logo image support~~ (Delayed)
- ~~Pull fonts from google fonts into the repo so full offline usage is possible~~

## Screens

![layout02-v4](https://cloud.githubusercontent.com/assets/790842/9316928/89998386-4538-11e5-98ee-cfa3d9fc4574.png)

/cc @Dignifiedquire @milmazz

**Comment by Dignifiedquire** [comment]
@josevalim thanks :)

**Comment by milmazz** [comment]
@Dignifiedquire In the `new_design` branch all the unit test are running smoothly :) Also, I already replaced all the references to *Glyphicons*, now  we're using *Font Awesome*, the HTML structure for those icons was adapted to avoid confusion in screen readers. Tonight I'll work with the footer & header. Let me know if you need more help :+1:

**Comment by Dignifiedquire** [comment]
Working on the sidebar now

**Comment by eksperimental** [comment]
One thing that we should switch to is using hyphens in element ids and drop the convention from the old design where it uses undescore, so "full_list" should be "full-list" now. I think that is the standard in bootstrap and now we have a hybrid of both "_ and -"

**Comment by Dignifiedquire** [comment]
@eksperimental yes I agree, I would also like to remove all usage of ids for styling and only use classes. See [this article](http://oli.jp/2011/ids/) for example as to why.

**Comment by eksperimental** [comment]
Another question is how many of the glyphicons are we use,
right now the fonts are 215kb, including one svg file which is 108kb.
Relevant discussion could be https://github.com/elixir-lang/elixir-lang.github.com/pull/456

**Comment by milmazz** [comment]
We need to decide if we want to keep with the `identifyExternalLinks` function (which adds an icon to any external link #189) in `events.js`. Right now the links to the *source code* include an icon also. So, at the right side of the source link we have 2 icons, this looks ugly IMHO. What do you think about this?

**Comment by josevalim** [comment]
We could also have a "data-no-external" attribute and not add the Source icon to links tagged with those. And then, of course, automatically tag the source with that. :)

**Comment by Dignifiedquire** [comment]
I think we can remove the local fonts point, it's too much work, and it will still work if you are offline, just not with less nice fonts.

**Comment by milmazz** [comment]
@Dignifiedquire In the `new_design` branch there is an updated version of `fillSidebarWithNodes`, this new version use Handlebars, let me know what do you think, any suggestion is more than welcome.

**Comment by Dignifiedquire** [comment]
@milmazz looking good, see some comments in IRC

**Comment by Dignifiedquire** [comment]
New target design:

![screen shot 2015-08-16 at 22 15 34](https://cloud.githubusercontent.com/assets/790842/9295718/eed00912-4477-11e5-9c35-f9fd76f289dd.png)

**Comment by eksperimental** [comment]
@Dignifiedquire It looks simply amazing.
I really, REALLY appreciate the simplicity and clarity of it

**Comment by mgwidmann** [comment]
Design looks fantastic! But, I'm curious... Why do the module names show in all caps on the left? Would `MyModule.SubModule` show up as `MYMODULE.SUBMODULE`? It looks good in the mock up, but this may become annoying when using it...

Just my $0.02 cents... Sorry if its a dumb question, I don't have time to pull it down and try it out...

**Comment by josevalim** [comment]
Oh, that's a very good point @mgwidmann. We can't show them in all caps. :D Sometimes it matters a lot, like `Plug.MIME` or `Plug.Mime`.

**Comment by Dignifiedquire** [comment]
Yes that was an oversight on my part. Will do an new revision tonight hopefully.

**Comment by josevalim** [comment]
@Dignifiedquire on my part too :D

**Comment by Dignifiedquire** [comment]
Alright. Version 3 Draft 1 incorporating the feedback I got so far. 

![layout02-v1](https://cloud.githubusercontent.com/assets/790842/9312647/3b1df6ca-451e-11e5-9ea9-1c1274a22eda.png)


// cc @josevalim @eksperimental @milmazz

**Comment by mgwidmann** [comment]
I kinda liked the purple...  was different. ¯\_(ツ)_/¯

**Comment by eksperimental** [comment]
I find it difficult to find the information now on the modules,
it could be because my eyes are tired, or because the lack of contrast. but I guess is a good condition to test it out.
I found the previous one much easier to spot along a long list.
Maybe full black, and a bit thicker...

**Comment by josevalim** [comment]
I really like the fonts, the small blue details (which maybe could be
purple, sorry! :D) and the overall organization. I do miss the detail that
makes the sidebar a bit different though.

I can think of two improvements, not sure if they help. Change the sidebar
links to a lighter color or add a light background. Another idea is to make
the left side easily collapsable so if it is too strong, you can just hide
it away when reading.

I think this is definitely an improvement!

I will get online soon and I can give more feedback.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Dignifiedquire** [comment]
> I kinda liked the purple... was different. ¯\_(ツ)_/¯

You'll have to talk that out with @josevalim ;)

> Also, maybe not repeating Phoenix a bunch of times would help find things. Maybe each sub module should be another tree? I haven't seen too many super nested modules like you see in the Java world, so I think this might be ok...

I would love to do some more nesting/visualization with these long lists are not great from any ui perspective. 


>I find it difficult to find the information now on the modules,
it could be because my eyes are tired, or because the lack of contrast. but I guess is a good condition to test it out.

Yes I can increase the thickness a bit (the color is already full on black). Also did you try viewing it in zoom-level 1:1? as that makes for some big difference compared to small inline preview

**Comment by tmjoen** [comment]
I think the last version with the white sidebar is far superior. Much cleaner and more professional looking. Nice work!

**Comment by Dignifiedquire** [comment]
Light and dark alternatives with improved readability:

![layout02-v2-dark](https://cloud.githubusercontent.com/assets/790842/9314090/ffbc1d7e-4526-11e5-9f58-05978ce74bd2.png)
![layout02-v2-light](https://cloud.githubusercontent.com/assets/790842/9314091/ffbf9c10-4526-11e5-9cdd-2724f37de29a.png)


we should not be using a light gray background, either fully commit to a dark sidebar or fully commit to a white sidebar.

There could be also the alternative of having the sidebar hidden by default, and only expand on button click, similar to what we do on the mobile view at the moment if you think the sidebar is taking up too much attention compared to the content.

**Comment by milmazz** [comment]
@Dignifiedquire I like all versions, really, the ones of this thread and the original proposal #150 

But, if I need to choose one, then:

* From the first version, I think that we don't need the sticky header at the top (almost empty) and I prefer the new organization in the sidebar area (present in newer versions). But I want to see in the newer versions some contrast (just a little) in the code samples.
* I really like the second version, I like the contrast between the sidebar and the content, I also like the colors, which represents Elixir identity. But, as @josevalim already mentioned, with this design we're imposing the Elixir identity over other Elixir projects (e.g. Phoenix)
* The latest version is also beautiful, clean and follows a minimalistic approach, I just miss a better contrast between the code samples and the content. Also a better contrast between the sidebar and the search area would be awesome.

So, for me, my first option is 2, but if we want to cover all Elixir project (as we do) I choose 3.

Also, If we want to collapse the sidebar, I think that Atlassian Confluence offers a really nice option:

![capture](https://cloud.githubusercontent.com/assets/34700/9313858/00add182-44eb-11e5-87c8-2acde70486e6.png)

Finally, this kind of decisions in the design area are really difficult (at least for me). This also makes me think about the *Themes Support in ExDoc* #218 (but this could imply a full rewrite of ExDoc), in this case I'll choose design ~2 for Elixir core projects (Elixir, IEx, EEx, etc.) and then design ~3 for the rest :)

**Comment by josevalim** [comment]
:+1: for the new dark layout. Outstanding. Beautiful.

**Comment by Dignifiedquire** [comment]
Latest version from irc: 
![layout02-v4-dark](https://cloud.githubusercontent.com/assets/790842/9315292/ba1bf318-452e-11e5-86b2-27ae48f7ef4b.png)

**Comment by josevalim** [comment]
Yes, yes, yes! I love the code colors!

**Comment by eksperimental** [comment]
Guys: all my PRs have been merged,
@milmazz if you want to rebase for one last time, so we can carry on from the new_design branch

thank you everyone

**Comment by eksperimental** [comment]
Ok, here is another suggestion,

One thing that I wanted to improve, in the current design and I think we should keep in mind, its a heading (but it doesn't not necessarily have to have a big font, in the current design i would make it bold)

in the new design, it looks smaller than the regular text, which is confusing.
the (`</>`) icon, which makes it look like code and even more confusing.
I suppose that's liking to the source code, but it makes the HEADING looks as such. ;-(

The rest looks simply SLICK!

Another thing is where are we going to show that what we are seeing is a function/callback/macro
Maybe having icons that can make people easily identify each of them would be great.
some ideas could be:
**function**: https://cdn1.iconfinder.com/data/icons/financial-data/100/Function-512.png
**callback**: a C letter, with an arrow pointing to itself. something like [this but with a C] (http://barhatov.com/media/images/callbacktwo.jpg)
**macro**: this is the most difficult i was able to come up with, maybe a building block like [this](http://smalldata.io/startup/common-files/icons/buildingblocks.png), [this](http://www.apptlantis.com/images/store_app_icons/0/4461/large.png?1347555057), [this](http://png-4.findicons.com/files/icons/2209/beos/128/beos_blocks.png), 

the macro one could be a bit difficult trying to convey the message, being a small icon.
well, just ideas, that maybe could lead to something good.

**Comment by milmazz** [comment]
@eksperimental Rebase done!, please review all the changes. Please, commit all the new features into `new_design`, only fix to bugs will be pushed into `master` (after that I can rebase again), in both cases via PR (as we usually do).

> Another thing is where are we going to show that what we are seeing is a function/callback/macro

We want to move that navigation bar into the sidebar, please check [this screenshot](https://cloud.githubusercontent.com/assets/790842/4030443/076a6136-2c5d-11e4-9114-f77d560844fc.png) to get a better idea, to accomplish this we need to decouple some things first, see: #302 

Any feedback is more than welcome.

**Comment by eksperimental** [comment]
@milmazz I have down a fresh pull from new_design and it says there are conflicts to merge.

**Comment by josevalim** [comment]
@eksperimental you should not get conflicts from pulling new-design, should you? Unless you have changes in new-design or you have accidentally pulled new-design into another branch like master.

**Comment by eksperimental** [comment]
@josevalim now it is working (yes i deleted the branch, create a new one from master, pulled it and tried to rebase from master and got that).,  
now it is working but the last revert was not there in the new design

**Comment by josevalim** [comment]
We may need to rebase again, yeah.

**Comment by milmazz** [comment]
@eksperimental @josevalim @Dignifiedquire Rebase done! Please let me know is there any issues after this.

**Comment by eksperimental** [comment]
@milmazz it worked flawlessly this time. thanks ;-D

**Comment by milmazz** [comment]
@Dignifiedquire I've been working with the EPUB support for ExDoc, I'm almost done with that feature. So, let me know if I can help you in some way. If you want I can work with the search feature (recently broken), or is there some task with higher priority?

**Comment by Dignifiedquire** [comment]
@milmazz it would be great if you could work on search, which is the main missing feature for the new design. The idea is that you type the query in the sidebar and when you hit enter it displays the results in the content area.
I hope to get the rest of the content styling done in the next couple of days :)

**Comment by Dignifiedquire** [comment]
@milmazz have you started on the search? Also what about the custom image support? Do you think it's important or should we leave it for the next iteration

**Comment by milmazz** [comment]
@Dignifiedquire Not yet, I haven't had so much time to work in this recently, if you can start with this feature please go ahead. Feel free to ping me if you have any questions.

About the custom image support, it would be great, but with the recent announcement of `Elixir-1.1.0-beta` I think we need to focus on small changes. I think it would be awesome if we can release v0.9 with the new Elixir version. In the next days I have one holiday, so, I can focus on pending tasks.

**Comment by milmazz** [comment]
@Dignifiedquire Have you been able to work on the search feature? Could you please update the list of pending tasks at the beginning of this issue?

Any feedback is greatly appreciate it.

**Comment by Dignifiedquire** [comment]
@milmazz sorry, my holidays didn't let me as much time for coding as I wished, updating the list now. No I haven't started on the search feature yet, but might be able to do some work on it tonight.

**Comment by milmazz** [comment]
@Dignifiedquire FYI, I already merge your last PR into `new_design`. I also rebase `new_design` changes on `master`. Please, when you have time, fix #318 history (which it is broken after the rebase process)

The build result for `new_design` is OK, there was a little issue with *ESLint*, but I already fix that.

The current status of the `new_design` branch is awesome, looks really great, excellent work!. My only suggestion is to improve the *animation effect* of the sidebar when you navigate between internal pages (e.g. In the `Kernel` module documentation you click on the `Kernel.SpecialForms` link), there is a *blink* in the sidebar when the new page is loading.

I hope that you can work on the search feature. Please, let me know if you need some help.

**Comment by Dignifiedquire** [comment]
@milmazz just finished the base implementation for search.
I've also pushed some fixes for eslint to the `new_design` branch.

About the blinking, I will take a look tomorrow

**Comment by josevalim** [comment]
Great job folks! I have been a bit away because I want to get the 1.1 beta out. I hope to have some ExDoc cycles in the next week. :)

**Comment by milmazz** [comment]
@Dignifiedquire I'll try to add all the Elixir code required to include the logo. I'll keep you posted!

I think that we're almost ready to merge `new_design` into `master` and receive some feedback. WDYT?

**Comment by milmazz** [comment]
@Dignifiedquire Do we need to restrict the format (e.g. PNG only) or dimensions (width or height) of the logo?

**Comment by Dignifiedquire** [comment]
We should restrict the format to `jpg|png` and leave a note that the image will be displayed in `64x64` but we not need to restrict the image in terms of size.

**Comment by milmazz** [comment]
@Dignifiedquire Got it! Thanks.

**Comment by milmazz** [comment]
@josevalim I think that we're ready to merge `new_design` into `master`, I think that @Dignifiedquire thinks the same :grinning: 

Would you do the honor? :shipit:

**Comment by josevalim** [comment]
Just be clear: @Dignifiedquire should do the honors :) Whenever you are ready!   :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by milmazz** [comment]
@josevalim :+1: /cc @Dignifiedquire
