### ISSUE TITLE
Issues and Suggestions

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#374]
## List of issues:

* __Footer__
  - [x] All issues Moved to #383
* __Sidebar__
  - [x] 1) Reduce size in version number: Moved to #366
  - [x] 2) If not logo provided, reduce size: Moved to #366
  - [x] 3) Overview white color/bolder: Obsolete b/c of changes in #395  ~~[Proposal](https://github.com/elixir-lang/ex_doc/issues/374#issuecomment-140719583)~~
* __Content Area__
  - [x] 1) Lineup title the Project name in sidebar. (cc0b0b2f63170a484c04e3c899cb62f139e58ef0)
  - [ ] 2) Linked Code
  - [x] 3) Underline color of Code inside link
* __General__
  - [x] 1) Rename html elements with underscore (assigned to: @eksperimental)
  - [ ] 2) External link ICON missing
  - [ ] 3) Vertical spacing Summary without description. [Proposal](https://github.com/elixir-lang/ex_doc/issues/374#issuecomment-140043635)

======

_Disclaimer: I apologize in advance for any duplicate reporting, specially on issues that have been discussed and agreed before, what I ´m looking as a reference are the current open issues, so if anything 's been discussed I appreciate a link to the discussion._

### FOOTER
**THE WHOLE FOOTER DISCUSSION HAS BEEN MOVED TO #383**
**FIXED in #387**

1) I think it should have the font a bit smaller (right now its 16px as the rest of the page)
**FIXED in #387**

2) Optionally a tad bit greyer, not full black.
**FIXED in #387**

3) Can we do a preferred breaking point in between the two sentences. Right now, if i used a zoomed view (125%) in my PC broswer , or in landscape view in my phone,  I see it like:
> Designed by Friedel Ziegelmayer and the ExDoc team. Built using ExDoc
> (v0.9.1-dev).

and I think it's better if it will be 
> Designed by Friedel Ziegelmayer and the ExDoc team.
> Built using ExDoc (v0.9.1-dev).

The only concern is that this won't add a fourth line to the portrait view in mobiles, but, if we the font sized is decided to be reduced a bit, it's quiet possible it will fit into three lines (that's the number it takes now).
there are tricks for this http://stackoverflow.com/a/24357132 but there could be one for CSS3, since that post is a bit old.
**FIXED in #387**

4) I will change the order of the sentences. I will go with:
> Built using ExDoc (v0.9.1-dev). Designed by Friedel Ziegelmayer and the ExDoc team.

instead of 
> Designed by Friedel Ziegelmayer and the ExDoc team. Built using ExDoc (v0.9.1-dev). 

the reason is that when I'm reading the docs, usually i see the copyright notice at the bottom of the page, and what for latter gives me the impression is that the current project that i'm reading its documentation has been designed by "Friedel Ziegelmayer & friends". Placing ExDoc before removes the ambiguity.
**FIXED in #387**

### SIDEBAR

1) I think the space in the sidebar is a [constant constraint](#366). One thing that we can definitly reduce its size is the version number. maybe may it bold? I know it will still be 64px high, because of the size of the logo, This will reduce the size with projects with long names: https://github.com/elixir-lang/ex_doc/issues/361#issuecomment-139825040
**DISCUSSION MOVED TO #366**

2) If no logo is provided, i think we can reduce the size of the header (most projects will not provide a logo i guess) (see point 1 for more info)
**DISCUSSION MOVED TO #366**

3) OVERVIEW should be WHITE when view the overview page. right now there is not distinction from when viewing any other page. and it's confusing, because what looks like it's being selected is MODULES. 
** OBSOLTE DUE TU CHANGES IN #395 **
~~**PROPOSAL: [HERE](https://github.com/elixir-lang/ex_doc/issues/374#issuecomment-140719583)**~~

### CONTENT AREA

1) (suggestion) Wouldn't it be neater to have the title of the page lined up at the same height of the project name in the side bar?
![ex_doc_title_linedup](https://cloud.githubusercontent.com/assets/9133420/9847567/fc70251e-5b03-11e5-9529-cef5b00c7fa4.png)

2) Link containing `code` doesn't display underline under the code area. Making it impossible to determine whether its a link to Module/function or not.
![ex_doc_code_link_underlined](https://cloud.githubusercontent.com/assets/9133420/9847823/0ea9b4e6-5b06-11e5-998f-c6691c219c20.png)

This behaviour is not consistent. When zoommed in (110%) it will show it.
See the difference between 100% and 110% zoom
![ex_doc_code_link](https://cloud.githubusercontent.com/assets/9133420/9847907/b96f4274-5b06-11e5-953a-4e93eb33d28c.png)
![ex_doc_code_link_zoomed](https://cloud.githubusercontent.com/assets/9133420/9847906/b967b694-5b06-11e5-9390-3490c567f2f1.png)

3) Change color of the underline for code inside links, I think pure black creates too much distraction. i find it too strong compared to how light code is styled. the challenged would be to make it work where code and regular text are part of the link.

### GENERAL

1) Get rid of the elements with underscore and use only hyphen. Example: `<h1 id="modules_summary" class="section-heading">Modules summary</h1>` 
I think this should be fixed ASAP, since we are going to start having people linking to from the sidebar to particular places like: Access.html#callbacks_details

2) External link ICON. We lost this feature in the new design. It's not possible to know know whether the link will still take you inside the docs or outside.

3) Vertical spacing Summary without description: It looks a bit odd when most of the elements in the summary have no description, but one does. http://elixir-lang.org/docs/master/elixir/overview.html#exceptions_summary
![ex_doc_exceptions_odd](https://cloud.githubusercontent.com/assets/9133420/9847561/ee699108-5b03-11e5-95cf-84d75cdc4f32.png)
**PROPOSAL: [HERE](https://github.com/elixir-lang/ex_doc/issues/374#issuecomment-140043635)**

_That's it for now. It looks really great. I'm impressed by the quality of everything. I will post more of the usual stuff as I get to use it. Thank you._

**Comment by josevalim** [comment]
Regarding the footer, maybe: "Built using ExDoc (v0.9.1-dev), designed by Friedel Ziegelmayer." It is more concise and because ExDoc is coming first to avoid the ambiguity, I would keep the design focus only on @Dignifiedquire.

**Comment by eksperimental** [comment]
@josevalim agreed on a 100%. excellent idea!

**Comment by josevalim** [comment]
> 1) (suggestion) Wouldn't it be neater to have the title of the page lined up at the same height of the project name in the side bar?

I honestly like the spacing today. It gives a lot of breathing room to the content which is more important than aligning it with the left side IMO.

> 1) Get rid of the elements with underscore and use only hyphen. Example: <h1 id="modules_summary" class="section-heading">Modules summary</h1> 
I think this should be fixed ASAP, since we are going to start having people linking to from the sidebar to particular places like: Access.html#callbacks_details

@eksperimental, can you please send a PR for this?

**Comment by Dignifiedquire** [comment]
Thanks @eksperimental for the detailed review. Below some of my comments & answers.

## Footer

I pretty much agree with everything you said here :)

@josevalim you were the one suggesting that I mention the rest of the team :stuck_out_tongue_closed_eyes:  But yes that would make it simpler

## Sidebar

1), 2) Yes we need to improve spacing a bit, but it's a balancing act between giving things room to breathe and creating enough space for the content. Let's continue the discussion around this in #366 

3) Yes it should, there is just no functionality at the moment doing that (also that needs to work for custom pages not only the `Overview` page.

## Content Area

1) Yes it would be

2), 3) The idea was that links turn purple inside code blocks not add problematic underlines in code blocks. There is a bug, where it does not disable the underlining in the inline code blocks atm.


## General

1) Need to think about it

2) We has some discussion with @josevalim and decided to drop it for now, as it was looking pretty bad and we felt it wasn't adding much anyway.

3) Well then people should write more descriptions :stuck_out_tongue_closed_eyes: 


I suggest we move individual items that we agreed upon into separate issues to make it easier to keep track of them.

**Comment by eksperimental** [comment]
@Dignifiedquire 

## General
> 3) Vertical spacing Summary without description: It looks a bit odd when most of the elements in the summary have no description, but one does. http://elixir-lang.org/docs/master/elixir/overview.html#exceptions_summary

*First Option, i just give a 0em bottom margin to `.summary-synopsis`,*
![ex_doc_summary_no_desc_fix](https://cloud.githubusercontent.com/assets/9133420/9848644/3445067c-5b0d-11e5-830b-82ced01a552e.png)

*Second Option, I give a 0em bottom margin to `.summary-synopsis`, and add 1em bottom margin to `.summary-row`*
![ex_doc_summary_fix_2](https://cloud.githubusercontent.com/assets/9133420/9848645/38ef9958-5b0d-11e5-9139-d15720e78b8e.png)

**Comment by eksperimental** [comment]
@josevalim  I will be ok sending a PR replacing the "_" with "-", but.. is there anything we need to consider @Dignifiedquire, or anything you want to say about it before I start?

**Comment by eksperimental** [comment]
> > 1) (suggestion) Wouldn't it be neater to have the title of the page lined up at the same height of the project name in the side bar?

> I honestly like the spacing today. It gives a lot of breathing room to the content which is more important than aligning it with the left side IMO.

@josevalim I was a bit afraid of that too. that it will look too packed. @Dignifiedquire since you think it's a good idea, can you please send of a screenshot of what it would look like? I think it will be easier to judge with something to actually look at.

**Comment by Dignifiedquire** [comment]
> @josevalim I will be ok sending a PR replacing the "_" with "-", but.. is there anything we need to consider @Dignifiedquire, or anything you want to say about it before I start?

No just make sure everything still works ;)

**Comment by Dignifiedquire** [comment]
> @josevalim I was a bit afraid of that too. that it will look too packed. @Dignifiedquire since you think it's a good idea, can you please send of a screenshot of what it would look like? I think it will be easier to judge with something to actually look at.

Will do some thinking on this

**Comment by eksperimental** [comment]
@Dignifiedquire regarding the external links, I don't agree with that it doesn't add much. Informing the user that he is going to go out of the website. The problem with using an icon is when it looks like it doesn't belong to the text; then I agree, it creates distraction. but if it's the same color as the link, same size, and it's actually a font-glyph like it could be http://fortawesome.github.io/Font-Awesome/icon/external-link/ I think it keeps the reading flow..

I will do a bit of research, and see what options are suitable for our project, without sacrificing the design. I'm sure there may be other options than icons to show it's a external link. such as title prefixing the link with "External", or other styling options.

**Comment by eksperimental** [comment]
> We have discussed this and there is no way to get around it for now. If both are selected (Overview and Modules), I think it would be equally confusing. The only option I can think is to keep the sidebar only for modules / protocols / exceptions navigation, moving the search and the linked pages to the content area. I would leave this up to @Dignifiedquire though, he very likely would have better ideas.

@josevalim I didn't mean to put the purple thing on the left, but to somehow distinguish it from the other pages.

I set overview to `color: white; font-weight: 500`; here's what it looks like.
![sidebar_overview_menu](https://cloud.githubusercontent.com/assets/9133420/9903966/67b37c1c-5ca4-11e5-878b-57c83a26be7c.png)

@Dignifiedquire what do you think?

**Comment by josevalim** [comment]
@eksperimental is there anything pending here to move to separate issues? :D The separate issues are great and much easier to track. :)

**Comment by eksperimental** [comment]
There are two proposal pending, i don't know if these issues have been fixed.

* __Sidebar__
  - 3) Overview chite color/bolder: [Proposal](https://github.com/elixir-lang/ex_doc/issues/374#issuecomment-140719583)
* __General__
  - 3) Vertical spacing Summary without description. [Proposal](https://github.com/elixir-lang/ex_doc/issues/374#issuecomment-140043635)

**Comment by Dignifiedquire** [comment]
@eksperimental https://github.com/elixir-lang/ex_doc/issues/374#issuecomment-140719583 is superfluous now that those are nested in the `Pages` category

**Comment by eksperimental** [comment]
@Dignifiedquire thank you, task list updated. it's shrinking!

**Comment by milmazz** [comment]
@eksperimental I'll close this issue, *it's really difficult to keep track of everything here*. If you think there are still some pending tasks, instead of reopen this issue, please try to create a new issue per task. IMHO, that way is more easy to keep our list of issues as tight as possible.

Sorry for the inconvenience!

**Comment by eksperimental** [comment]
No worries, thanks for taking care of this, i completely forgot about this list.
I have updated the list, and only one task is pending, and I have created an issue for it.
