### ISSUE TITLE
What do we want to see in the next version of ExDoc?

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#483]
After the release of ExDoc 0.10 we have introduced new bug fixes and new features. The idea of this thread is to open the discussion about the things that we want to see in the next version of ExDoc.

So far, the following are some of the improvements already done in this iteration:

* [x] Increase the visual separation between functions #419
* [x] Allow to define the title in the sidebar area for additional content, default: Pages. #467
* [x] Allow to define the path and title of each additional page in `mix.exs`. #470
* [x] Use the first `h1` as menu title if title is not configured. #471
* [x] Remove the `extra-` prefix for the additional documentation. #462 #468
* [x] Extra large images do not create an overflow in the content. #455
* [x] Include the project name as part of the header in small devices. #435 #458

However, there is a lot of work still pending, such as:

* [ ] Night mode version for docs. #474
* [ ] Link icon overlaps with hamburger (in small devices) #434
* [ ] Add history support to the search page #341
* [ ] EPUB support (I can complete this feature this weekend) #305

What do you think? /cc @josevalim @eksperimental @Dignifiedquire

**Comment by josevalim** [comment]
Thanks @milmazz! Most of those would be really nice improvements, although they should not block it because we already have enough IMO. So I think the big question is if there are any bugs or improvements that are extremely important to include so we focus our efforts on it. :)

**Comment by ericmj** [comment]
All of these fixes seem enough for it's own release.

**Comment by milmazz** [comment]
> So I think the big question is if there are any bugs or improvements that are extremely important to include so we focus our efforts on it

@josevalim AFAIK there is nothing extremely urgent to fix. Also, as you and @ericmj pointed out, there is a lot of things already done for a new release :-D

I'll send a PR with the updated Changelog.

**Comment by josevalim** [comment]
Closing then in favor of the CHANGELOG. :D
